CREATE TABLE "audit_event" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"action" text NOT NULL,
	"actor_id" text NOT NULL,
	"target_type" text NOT NULL,
	"target_id" text NOT NULL,
	"details" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth_account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"issuer" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"password" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth_session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"legacy_user_id" text,
	"disabled" boolean DEFAULT false NOT NULL,
	"password_reset_required" boolean DEFAULT false NOT NULL,
	"failed_login_attempts" integer DEFAULT 0 NOT NULL,
	"lockout_end" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "permission" (
	"name" text PRIMARY KEY NOT NULL,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "role_permission" (
	"role_code" text NOT NULL,
	"permission_name" text NOT NULL,
	CONSTRAINT "role_permission_role_code_permission_name_pk" PRIMARY KEY("role_code","permission_name")
);
--> statement-breakpoint
CREATE TABLE "role" (
	"code" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_role" (
	"user_id" text NOT NULL,
	"role_code" text NOT NULL,
	"assigned_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_role_user_id_role_code_pk" PRIMARY KEY("user_id","role_code")
);
--> statement-breakpoint
CREATE TABLE "bachelor" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bachelor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_code" varchar(20) NOT NULL,
	"full_name" varchar(100) NOT NULL,
	"mail" varchar(100),
	"faculty" varchar(50),
	"major" varchar(50),
	"image" varchar(250),
	"status" boolean DEFAULT false,
	"bachelor_status" varchar(50),
	"hall_id" integer,
	"session_id" integer,
	"chair" varchar(50),
	"chair_parent" varchar(50),
	"session_in_day" integer,
	"check_in" boolean,
	"time_check_in" timestamp with time zone,
	"attendance_status" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "bachelor_attendance_status_check" CHECK ("bachelor"."attendance_status" between 0 and 3)
);
--> statement-breakpoint
CREATE TABLE "check_in" (
	"checkin_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "check_in_checkin_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"hall_id" integer,
	"session_id" integer,
	"status" boolean
);
--> statement-breakpoint
CREATE TABLE "hall" (
	"hall_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hall_hall_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"hall_name" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notification" (
	"notification_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(200) NOT NULL,
	"content" varchar(1000) NOT NULL,
	"priority" integer DEFAULT 2 NOT NULL,
	"hall_id" integer,
	"session_id" integer,
	"created_by" text NOT NULL,
	"broadcast_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"scheduled_at" timestamp with time zone,
	"broadcast_at" timestamp with time zone,
	"status" varchar(20) DEFAULT 'PENDING' NOT NULL,
	"is_automatic" boolean DEFAULT false NOT NULL,
	"repeat_count" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "notification_priority_check" CHECK ("notification"."priority" between 1 and 3),
	CONSTRAINT "notification_repeat_count_check" CHECK ("notification"."repeat_count" between 1 and 10),
	CONSTRAINT "notification_status_check" CHECK ("notification"."status" in ('PENDING', 'BROADCASTING', 'COMPLETED', 'CANCELLED'))
);
--> statement-breakpoint
CREATE TABLE "session" (
	"session_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_number" integer,
	"session_in_day" integer,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "legacy_identity_credential" (
	"legacy_user_id" text PRIMARY KEY NOT NULL,
	"auth_user_id" text NOT NULL,
	"aspnet_password_hash" text,
	"password_reset_required" boolean DEFAULT false NOT NULL,
	"migrated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "legacy_media_mapping" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "legacy_media_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"old_path" text NOT NULL,
	"media_id" uuid NOT NULL,
	"sha256" varchar(64) NOT NULL,
	"migrated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "media_asset" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"object_key" varchar(512) NOT NULL,
	"original_name" varchar(255) NOT NULL,
	"content_type" varchar(100) NOT NULL,
	"size" bigint NOT NULL,
	"width" integer,
	"height" integer,
	"sha256" varchar(64) NOT NULL,
	"owner_type" varchar(50) NOT NULL,
	"owner_id" varchar(100) NOT NULL,
	"status" integer DEFAULT 0 NOT NULL,
	"uploaded_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "media_asset_status_check" CHECK ("media_asset"."status" between 0 and 2),
	CONSTRAINT "media_asset_size_check" CHECK ("media_asset"."size" >= 0)
);
--> statement-breakpoint
INSERT INTO "role" ("code", "name") VALUES
  ('MN', 'Quản lý'),
  ('CK', 'Nhân viên check-in'),
  ('MC', 'Người dẫn chương trình'),
  ('US', 'Người dùng'),
  ('NO', 'Người đọc thông báo');
--> statement-breakpoint
INSERT INTO "permission" ("name", "description") VALUES
  ('system.manage', 'Quản trị hệ thống'),
  ('halls.manage', 'Quản lý hội trường'),
  ('sessions.manage', 'Quản lý phiên'),
  ('bachelors.manage', 'Quản lý tân cử nhân'),
  ('checkin.execute', 'Thực hiện check-in'),
  ('led.control', 'Điều khiển màn hình LED'),
  ('notifications.manage', 'Quản lý thông báo'),
  ('notifications.broadcast', 'Phát thông báo'),
  ('media.manage', 'Quản lý media');
--> statement-breakpoint
INSERT INTO "role_permission" ("role_code", "permission_name") VALUES
  ('MN', 'system.manage'), ('MN', 'halls.manage'), ('MN', 'sessions.manage'),
  ('MN', 'bachelors.manage'), ('MN', 'checkin.execute'), ('MN', 'led.control'),
  ('MN', 'notifications.manage'), ('MN', 'notifications.broadcast'), ('MN', 'media.manage'),
  ('CK', 'checkin.execute'),
  ('MC', 'led.control'),
  ('US', 'led.control'),
  ('NO', 'notifications.manage'), ('NO', 'notifications.broadcast');
--> statement-breakpoint
ALTER TABLE "auth_account" ADD CONSTRAINT "auth_account_user_id_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_session" ADD CONSTRAINT "auth_session_user_id_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permission" ADD CONSTRAINT "role_permission_role_code_role_code_fk" FOREIGN KEY ("role_code") REFERENCES "public"."role"("code") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permission" ADD CONSTRAINT "role_permission_permission_name_permission_name_fk" FOREIGN KEY ("permission_name") REFERENCES "public"."permission"("name") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_role" ADD CONSTRAINT "user_role_user_id_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_role" ADD CONSTRAINT "user_role_role_code_role_code_fk" FOREIGN KEY ("role_code") REFERENCES "public"."role"("code") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bachelor" ADD CONSTRAINT "bachelor_hall_id_hall_hall_id_fk" FOREIGN KEY ("hall_id") REFERENCES "public"."hall"("hall_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bachelor" ADD CONSTRAINT "bachelor_session_id_session_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("session_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "check_in" ADD CONSTRAINT "check_in_hall_id_hall_hall_id_fk" FOREIGN KEY ("hall_id") REFERENCES "public"."hall"("hall_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "check_in" ADD CONSTRAINT "check_in_session_id_session_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("session_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification" ADD CONSTRAINT "notification_hall_id_hall_hall_id_fk" FOREIGN KEY ("hall_id") REFERENCES "public"."hall"("hall_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification" ADD CONSTRAINT "notification_session_id_session_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."session"("session_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification" ADD CONSTRAINT "notification_created_by_auth_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."auth_user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification" ADD CONSTRAINT "notification_broadcast_by_auth_user_id_fk" FOREIGN KEY ("broadcast_by") REFERENCES "public"."auth_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "legacy_identity_credential" ADD CONSTRAINT "legacy_identity_credential_auth_user_id_auth_user_id_fk" FOREIGN KEY ("auth_user_id") REFERENCES "public"."auth_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "legacy_media_mapping" ADD CONSTRAINT "legacy_media_mapping_media_id_media_asset_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media_asset"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "media_asset" ADD CONSTRAINT "media_asset_uploaded_by_auth_user_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."auth_user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_event_actor_created_idx" ON "audit_event" USING btree ("actor_id","created_at");--> statement-breakpoint
CREATE INDEX "audit_event_target_idx" ON "audit_event" USING btree ("target_type","target_id");--> statement-breakpoint
CREATE UNIQUE INDEX "auth_account_issuer_account_uidx" ON "auth_account" USING btree ("issuer","account_id");--> statement-breakpoint
CREATE INDEX "auth_account_user_id_idx" ON "auth_account" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "auth_session_token_uidx" ON "auth_session" USING btree ("token");--> statement-breakpoint
CREATE INDEX "auth_session_user_id_idx" ON "auth_session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "auth_session_expires_at_idx" ON "auth_session" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "auth_user_email_normalized_uidx" ON "auth_user" USING btree (lower("email"));--> statement-breakpoint
CREATE UNIQUE INDEX "auth_user_legacy_user_id_uidx" ON "auth_user" USING btree ("legacy_user_id") WHERE "auth_user"."legacy_user_id" is not null;--> statement-breakpoint
CREATE INDEX "auth_verification_identifier_idx" ON "auth_verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "auth_verification_expires_at_idx" ON "auth_verification" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "bachelor_student_code_normalized_uidx" ON "bachelor" USING btree (lower("student_code"));--> statement-breakpoint
CREATE INDEX "bachelor_hall_id_idx" ON "bachelor" USING btree ("hall_id");--> statement-breakpoint
CREATE INDEX "bachelor_session_id_idx" ON "bachelor" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "bachelor_hall_session_idx" ON "bachelor" USING btree ("hall_id","session_id");--> statement-breakpoint
CREATE INDEX "bachelor_check_in_idx" ON "bachelor" USING btree ("check_in");--> statement-breakpoint
CREATE INDEX "check_in_hall_id_idx" ON "check_in" USING btree ("hall_id");--> statement-breakpoint
CREATE INDEX "check_in_session_id_idx" ON "check_in" USING btree ("session_id");--> statement-breakpoint
CREATE UNIQUE INDEX "check_in_hall_session_uidx" ON "check_in" USING btree ("hall_id","session_id");--> statement-breakpoint
CREATE UNIQUE INDEX "hall_name_normalized_uidx" ON "hall" USING btree (lower("hall_name"));--> statement-breakpoint
CREATE INDEX "notification_status_created_idx" ON "notification" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "notification_scheduled_at_idx" ON "notification" USING btree ("scheduled_at");--> statement-breakpoint
CREATE INDEX "notification_hall_id_idx" ON "notification" USING btree ("hall_id");--> statement-breakpoint
CREATE INDEX "notification_session_id_idx" ON "notification" USING btree ("session_id");--> statement-breakpoint
CREATE UNIQUE INDEX "session_number_uidx" ON "session" USING btree ("session_number") WHERE "session"."session_number" is not null;--> statement-breakpoint
CREATE INDEX "session_in_day_idx" ON "session" USING btree ("session_in_day");--> statement-breakpoint
CREATE INDEX "legacy_identity_auth_user_id_idx" ON "legacy_identity_credential" USING btree ("auth_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "legacy_media_mapping_old_path_uidx" ON "legacy_media_mapping" USING btree ("old_path");--> statement-breakpoint
CREATE INDEX "legacy_media_mapping_media_id_idx" ON "legacy_media_mapping" USING btree ("media_id");--> statement-breakpoint
CREATE INDEX "legacy_media_mapping_sha256_idx" ON "legacy_media_mapping" USING btree ("sha256");--> statement-breakpoint
CREATE UNIQUE INDEX "media_asset_object_key_uidx" ON "media_asset" USING btree ("object_key");--> statement-breakpoint
CREATE INDEX "media_asset_sha256_idx" ON "media_asset" USING btree ("sha256");--> statement-breakpoint
CREATE INDEX "media_asset_owner_idx" ON "media_asset" USING btree ("owner_type","owner_id");--> statement-breakpoint
CREATE INDEX "media_asset_status_created_idx" ON "media_asset" USING btree ("status","created_at");
