CREATE TABLE "photo_queue_session" (
	"photo_queue_session_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "photo_queue_session_photo_queue_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(120) NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_kiosk_active" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "photo_queue_state" (
	"photo_queue_state_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "photo_queue_state_photo_queue_state_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"photo_session_id" integer NOT NULL,
	"current_number" integer DEFAULT 0 NOT NULL,
	"current_photo_confirmed" boolean DEFAULT true NOT NULL,
	"current_photo_taken" boolean,
	"manual_return_number" integer,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" text,
	CONSTRAINT "photo_queue_state_current_number_check" CHECK ("photo_queue_state"."current_number" >= 0),
	CONSTRAINT "photo_queue_state_manual_return_number_check" CHECK ("photo_queue_state"."manual_return_number" is null or "photo_queue_state"."manual_return_number" >= 0)
);
--> statement-breakpoint
CREATE TABLE "photo_queue_entry" (
	"photo_queue_entry_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "photo_queue_entry_photo_queue_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bachelor_id" integer NOT NULL,
	"photo_session_id" integer NOT NULL,
	"queue_number" integer NOT NULL,
	"photo_status" varchar(20) DEFAULT 'WAITING' NOT NULL,
	"source" varchar(20) DEFAULT 'KIOSK' NOT NULL,
	"coordinator_reason" text,
	"retouch_note_image_1" text,
	"retouch_note_image_2" text,
	"requested_at" timestamp with time zone DEFAULT now() NOT NULL,
	"photographed_at" timestamp with time zone,
	CONSTRAINT "photo_queue_entry_number_check" CHECK ("photo_queue_entry"."queue_number" > 0),
	CONSTRAINT "photo_queue_entry_status_check" CHECK ("photo_queue_entry"."photo_status" in ('WAITING', 'PHOTOGRAPHED'))
);
--> statement-breakpoint
CREATE TABLE "photo_queue_assignment" (
	"photo_queue_assignment_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "photo_queue_assignment_photo_queue_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bachelor_id" integer NOT NULL,
	"photo_session_id" integer NOT NULL,
	"requires_coordinator" boolean DEFAULT false NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "photo_queue_audit_log" (
	"photo_queue_audit_log_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "photo_queue_audit_log_photo_queue_audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"photo_session_id" integer NOT NULL,
	"action" varchar(40) NOT NULL,
	"previous_number" integer,
	"next_number" integer,
	"actor_id" text,
	"actor_name" text,
	"details" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "photo_queue_state" ADD CONSTRAINT "photo_queue_state_photo_session_id_fk" FOREIGN KEY ("photo_session_id") REFERENCES "public"."photo_queue_session"("photo_queue_session_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "photo_queue_state" ADD CONSTRAINT "photo_queue_state_updated_by_auth_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."auth_user"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "photo_queue_entry" ADD CONSTRAINT "photo_queue_entry_bachelor_id_bachelor_id_fk" FOREIGN KEY ("bachelor_id") REFERENCES "public"."bachelor"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "photo_queue_entry" ADD CONSTRAINT "photo_queue_entry_photo_session_id_fk" FOREIGN KEY ("photo_session_id") REFERENCES "public"."photo_queue_session"("photo_queue_session_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "photo_queue_assignment" ADD CONSTRAINT "photo_queue_assignment_bachelor_id_bachelor_id_fk" FOREIGN KEY ("bachelor_id") REFERENCES "public"."bachelor"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "photo_queue_assignment" ADD CONSTRAINT "photo_queue_assignment_photo_session_id_fk" FOREIGN KEY ("photo_session_id") REFERENCES "public"."photo_queue_session"("photo_queue_session_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "photo_queue_audit_log" ADD CONSTRAINT "photo_queue_audit_log_photo_session_id_fk" FOREIGN KEY ("photo_session_id") REFERENCES "public"."photo_queue_session"("photo_queue_session_id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "photo_queue_audit_log" ADD CONSTRAINT "photo_queue_audit_log_actor_id_auth_user_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."auth_user"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "photo_queue_session_name_uidx" ON "photo_queue_session" USING btree (lower("name"));
--> statement-breakpoint
CREATE UNIQUE INDEX "photo_queue_state_photo_session_uidx" ON "photo_queue_state" USING btree ("photo_session_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "photo_queue_entry_bachelor_photo_session_uidx" ON "photo_queue_entry" USING btree ("bachelor_id","photo_session_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "photo_queue_entry_photo_session_number_uidx" ON "photo_queue_entry" USING btree ("photo_session_id","queue_number");
--> statement-breakpoint
CREATE INDEX "photo_queue_entry_photo_session_idx" ON "photo_queue_entry" USING btree ("photo_session_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "photo_queue_assignment_bachelor_uidx" ON "photo_queue_assignment" USING btree ("bachelor_id");
--> statement-breakpoint
CREATE INDEX "photo_queue_assignment_photo_session_idx" ON "photo_queue_assignment" USING btree ("photo_session_id");
--> statement-breakpoint
CREATE INDEX "photo_queue_audit_photo_session_created_idx" ON "photo_queue_audit_log" USING btree ("photo_session_id","created_at");
--> statement-breakpoint
INSERT INTO "permission" ("name", "description") VALUES
	('photo-queue.request', 'Request a photo queue number for a bachelor'),
	('photo-queue.control', 'Control the active photo queue number')
ON CONFLICT ("name") DO NOTHING;
--> statement-breakpoint
INSERT INTO "role" ("code", "name") VALUES
	('PQ', 'Photo Queue Kiosk'),
	('PC', 'Photo Queue Coordinator')
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
INSERT INTO "role_permission" ("role_code", "permission_name") VALUES
	('PQ', 'photo-queue.request'),
	('PC', 'photo-queue.control')
ON CONFLICT DO NOTHING;
