// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FA23_Convocation2023_API.Models
{
    public partial class Bachelor
    {
        public int Id { get; set; }
        public string StudentCode { get; set; }
        public string FullName { get; set; }
        public string Mail { get; set; }
        public string Faculty { get; set; }
        public string Major { get; set; }
        public string Image { get; set; }
        public bool? Status { get; set; }
        public string StatusBaChelor { get; set; }
        public int? HallId { get; set; }
        public int? SessionId { get; set; }
        public string Chair { get; set; }
        public string ChairParent { get; set; }
        public bool? CheckIn { get; set; }
        public DateTime? TimeCheckIn { get; set; }

        public virtual Hall Hall { get; set; }
        public virtual Session Session { get; set; }
    }
}