// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FA23_Convocation2023_API.Models
{
    public partial class CheckIn
    {
        public int CheckinId { get; set; }
        public int? HallId { get; set; }
        public int? SessionId { get; set; }
        public bool? Status { get; set; }

        public virtual Hall Hall { get; set; }
        public virtual Session Session { get; set; }
    }
}