// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FA23_Convocation2023_API.Models
{
    public partial class Hall
    {
        public Hall()
        {
            Bachelors = new HashSet<Bachelor>();
            CheckIns = new HashSet<CheckIn>();
        }

        public int HallId { get; set; }
        public string HallName { get; set; }

        public virtual ICollection<Bachelor> Bachelors { get; set; }
        public virtual ICollection<CheckIn> CheckIns { get; set; }
    }
}